import React, { useState } from "react";
import { FiFileText, FiX } from "react-icons/fi";

const reports = [
  { id: 1, title: "School Performance Report", size: "2.3MB" },
  { id: 2, title: "Full Match Log", size: "1.8MB" },
  { id: 3, title: "Sponsor Executive Sumamry", size: "3.1MB" },
  { id: 4, title: "System Performance", size: "2.5MB" },
];

const Report = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalType, setModalType] = useState("");
  const [currentReport, setCurrentReport] = useState(null);

  const openModal = (type, report) => {
    setModalType(type);
    setCurrentReport(report);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
  };

  return (
    <div className="p-4 space-y-4">
      <p className="font-semibold text-2xl mb-4">Reports & Analytics</p>

      {/* REPORT CARDS */}
      <div className="grid grid-cols-1 gap-4">
        {reports.map((report) => (
          <div
            key={report.id}
            className="border border-[#E2E8F0] bg-[#F8FAFC] rounded-lg p-4 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4"
          >
            {/* Left */}
            <div className="flex items-center gap-3">
              <FiFileText className="text-[#001489] text-2xl" />
              <div>
                <p className="font-semibold text-base sm:text-lg">{report.title}</p>
                <p className="text-sm text-gray-500">{report.size}</p>
              </div>
            </div>

            {/* Buttons */}
            <div className="flex flex-col sm:flex-row gap-2 w-full sm:w-auto">
              <button
                onClick={() => openModal("view", report)}
                className="px-4 py-2 bg-[#001489] text-white rounded-md w-full sm:w-auto hover:bg-[#001173]"
              >
                View
              </button>
              <button
                onClick={() => openModal("download", report)}
                className="px-4 py-2 border border-[#001489] rounded-md text-[#001489] w-full sm:w-auto hover:bg-[#E8EDFF]"
              >
                Download All
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* MODAL */}
      {isModalOpen && currentReport && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white w-full max-w-md rounded-xl p-6 shadow-xl space-y-5 relative animate-fadeIn">

            {/* Close Icon */}
            <FiX
              className="absolute top-4 right-4 text-gray-500 text-xl cursor-pointer hover:text-black"
              onClick={closeModal}
            />

            {/* Modal Title */}
            <p className="text-center text-xl font-semibold">
              {modalType === "view" ? "Download Report" : "Download All Reports"}
            </p>

            {/* VIEW CONTENT */}
            {modalType === "view" && (
              <div className="space-y-2 text-sm text-gray-700 text-center">
                <p>Your report is ready to download.</p>
                <p>Please review the details below before continuing.</p>

                <div className="bg-gray-100 rounded-md p-3 text-left space-y-1 mt-3">
                  <p><strong>File Name:</strong> {currentReport.title.replace(/\s/g, "_")}_2025.pdf</p>
                  <p><strong>Size:</strong> {currentReport.size}</p>
                  <p><strong>Generated By:</strong> System</p>
                  <p><strong>Date Prepared:</strong> 10-10-2025</p>
                </div>
              </div>
            )}

            {/* DOWNLOAD LIST */}
            {modalType === "download" && (
              <div className="space-y-4 text-sm text-gray-700">
                <p className="font-semibold text-center border-b pb-2">
                  System Performance Reports
                </p>

                {[1, 2, 3, 4, 5, 6].map((i) => (
                  <div
                    key={i}
                    className="flex justify-between items-center border-b pb-2"
                  >
                    <p className="w-[65%]">{currentReport.title} - Section {i}</p>
                    <button className="bg-[#001489] text-white py-1 px-3 rounded hover:bg-[#001173] text-xs">
                      Download
                    </button>
                  </div>
                ))}
              </div>
            )}

            {/* BUTTONS */}
            <div className="flex justify-between pt-4">
              <button
                onClick={closeModal}
                className="px-4 py-2 bg-gray-200 rounded-md hover:bg-gray-300"
              >
                Cancel
              </button>

              {modalType === "view" && (
                <button className="px-4 py-2 bg-[#001489] text-white rounded-md hover:bg-[#001173]">
                  Download Report
                </button>
              )}

              {modalType === "download" && (
                <button className="px-4 py-2 bg-[#001489] text-white rounded-md hover:bg-[#001173]">
                  Download All
                </button>
              )}
            </div>

          </div>
        </div>
      )}
    </div>
  );
};

export default Report;
